version: '3.8'

services:
  base-project:
    image: ghcr.io/anhnmt/golang-grpc-base-project:latest
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    networks:
      - base-project
    restart: "always"
    volumes:
      - ./logs:/root/logs
    deploy:
     replicas: 1

networks:
  base-project:
    external: true