// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/anhnmt/golang-grpc-base-project/internal/grpc_server"
	"github.com/anhnmt/golang-grpc-base-project/internal/pkg/database"
	"github.com/anhnmt/golang-grpc-base-project/internal/server"
)

// Injectors from wire.go:

func InitServer(ctx context.Context) (*server.Server, error) {
	client, err := database.New(ctx)
	if err != nil {
		return nil, err
	}
	grpcServer := grpc_server.New()
	serverServer := server.New(client, grpcServer)
	return serverServer, nil
}
