// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/anhnmt/golang-grpc-base-project/internal/grpc_server"
	"github.com/anhnmt/golang-grpc-base-project/internal/server"
)

// Injectors from wire.go:

func InitServer() (*server.Server, error) {
	grpcServer := grpc_server.New()
	serverServer := server.New(grpcServer)
	return serverServer, nil
}
