[app]
name = "golang-grpc-base-project"
address = "localhost:5000"
debug = true

[pprof]
address = "localhost:6060"

[log]
payload = true

[seeder]
service = true

[cors]
debug = false
enabled = true

[database]
url = "mongodb://root:123456aA%40@localhost:27017"
name = "base"

[redis]
url = "localhost:16379"
password = ""
db = 0

[casbin]
name = "roles"
model = """
[request_definition]
r = sub, obj

[policy_definition]
p = sub, obj

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (g(r.sub, p.sub) || keyMatch(r.sub, p.sub)) && keyMatch(r.obj, p.obj)
"""

[jwt]
signKey = """
-----BEGIN RSA PRIVATE KEY-----
MIIJKQIBAAKCAgEArseWOZbqb74FUcqDbbXdeYDhR4qZ8qzSwhMI2AVK+Ex69tXo
I6mYLLKde92gFRrrD/CQOrDAX4HPEjJwA9l6HdWtsxtQUMrsycox1AEPxIbZHNsH
L5i/G+CkRfUUNi5Up4WOA4Z1CfLhEzxJMPfwQbBIPQOM4g7gTUiDjoB9KU7WWXN+
os5cEoWSOKT/2xLBRHJPuq8ysZ7XblFaLGr2sIgg48PZ7d1FgOzUuh68/XOY5VJh
fraZam4K85pvgNESIv0NEFBAFwsWwiQc/m0A5tTiCdKV4/Gcb4g2mEvshgXm7yDu
bRgb+cAtDE5+Qxnmof0s4mHB5dEGerYLrcp0mEhZyaR5eZpIGVuNDGFbbZksbkI3
r+aLTkKer9QlbcJl9gzGUjgVWJHGdYiRAWQURPUpKdcHobjXwvArehAaBi3fMNXj
5wbkAYKos9qXOO1YKX7EYAlAAMNamA4elaJ2dBl5a/8uCFxIebRpZHIhHqyS7pS4
SJfEF8W1hZ1fkujz4VePCo/rhKLHhGd7GOVd3EGGr6OJ0vGHnBqF0PhaVr5VJPDR
fvQxAigW6k0QaGkqItRKtri9QFDGi0Vu4xmigtr7EyW5Quw+rikHNOC0WAfrwtRt
4qU4wvf6gN51ETG1N5I/+d1ethmHurdrL7IpBBsVeb/OwAwva1nsNkyf7x8CAwEA
AQKCAgAYhv/I8ynRJpx+fun0wnnjLDfxHz09dg1ZmOw7zHpZ3/m9nAUoxAsL8sDw
+ggWDiIAqaTD57wHayMRDaz0jVd6ylrG8MVToTabltlpRADfdoEPcJlQj6H6GotT
GfKNK/FLVQ255uuTytbVKTeoPJMl1MQ+c7oYmzfVAKEdpWBrJJomEXQrCsSXANGl
S1pwdvBSV6xiqWV20bCv1ZDO/O/DlEbxT7HMlKnFTvcHa3rgIpHJVMdDzgI3klvN
FdYiALUH3fUwXeKwmSjHc+PxvIBM5IEYGcpZI7XtXPM0ais2H6vp0PhErQZ4BQUN
XhKP/hmEkA/1cPyR8MR1AgkfiXLVFGerkt964rYGtV++C6e3iIQhlCeCLyQL5pP1
qJd7DzNGC6N1JlUjrcl3E2VFwiQBT7BTs4/2n6gtGwdfYxqx8aJSA4EwGnD78uFT
WvF/TNZKsd2caHzj+D6+EkAPgW8tesb3wAwuzQlbAkeKLiXHdXVU4M3BxyEFficO
5QtPxeuCdD0u5GSfuVvfuv+zq/Vqnc0Ji+gsDMShaXzdVvbTrvx1xvc3bux6JUFI
YvKjl4gD07W3vQzHVGxz0hQFShbyMcBtRsb+7wLHWEkIkMvfEBxZNA6eg7F8gGQW
IpsCopig8kNdi2y7H98a7elcVBUpX5CfUVHedOzgFjrL27bwGQKCAQEA6IBDc6Su
ZivjnAT3z4qeyfya7MGiHatu+2Bq8MX4uogtitvnFiutUUwI6SAoQR5X8vyS4XxC
PFy9wBzQs2k5Z2mTuzOJmcuzmMS2yhJWZVLfTegdJU0rl1yPmHF0sKTuUaye+Pr4
L/C5qxabO4zRleC7jmw/oKAYkOmML59lmYNN9KkDyNhRY31aXXEkbkGLMwUMNqkl
T9gq6rRjKcGXUFqpyDO3jZJVZlqC0XnmKMMyaNCzIoJuR0vFGx91in3fki+uMbnK
UGLQ5tZEuzzCSDHzjTtufwbAtzteMTVo3TgHPnf40IvEDMUAnImCUkf/v76qHtT1
EmZ6Ki0oUp1xuwKCAQEAwHHWuwgEZkWIkxD2RhxRxGyICCH0U0O3O+Pv+b+cCWNU
WpITWKDvcze8LfmZGqwfSY25OjH9NfrKT4aJOh3307q8+vqj3AQAbJ/szSJelVZU
vGrabBwgmfMAYz7ogkqxAn3t3olF3HOVg7MG9dX5qPnIMIFZ24ihrNzB80xN5hqG
3hRI7P/9m/3y9PvEp2b0XAl23N3I2yVf7PpoN4fVc9HgTL8dRLgWHs4Iq3a0vWSX
TJ6+c2TB6jLsuuP5WCJgEiMExuW7TTuGGtl78HTxzOFh7ihHKKwzIodzUuREm4t7
H5TncpTp2Xtc99Q55uTKN3zPL2AQw6LkIP82Usgf7QKCAQEAtDdPkWDx6bJVYAcd
ytppEKnjsGa68YKDqQfofK8HiBasLnkbmzzJwD1Ont1VNnx9sZQDihJWCRHd5v6u
6pJCc50LbMya+QJDOMQp52HlY+6jtnCXvuUdR9rwVzqCN7XwIJDMPLPUEtzmHe6M
7tDNV/51gwT3INtXj2PoTLWh/CciEuW7UEAUfiiZFdrwYSIe8rIT8H6VtFkbkwe1
4ZT0Y82S0uL7gRoPZiH8SsDRHYGIHmS+pZ4yOsNJiieNZYcB9/9LZ7HaVwrxYCxv
5C5JbcqCPVP25zFlyeGTtlLu8KJQQySdUZE0qq09NxkDUiIK5Ca3GOT6/YM/aFfO
bJMrpwKCAQAVJGyS366cDceTYKmtyi6xhbrsKc7N1wKqccBLj+F0ppT93k6BziyA
W/8wjdtkMsS9L/TJj/RhmcvgMMeiuugfOsTITgDyiv4A8RDy+HOrtHBawuJ8PhrW
zvub661foxUPUQZxDGPAdHJYpbJ+D6P+DHMR4SQeGkSo2Rf1wsxMG131yAS7BOS3
3o5ym7ZfLdBqzB9i5HrMmK6ROnF4qFOrBcO+qsBsbE0B1WDedYwlwodcw5Po2Yj0
UePwJFugcyZa174Om+6X7ZIuIPac1Dw8ZgZ8Q7CNp112zaq90JY5AHnmXlWPIQ0P
952fHJG/7CLLNcsNSWCOHbcyaNdvAM2BAoIBAQDefft/qh4AVNkvoatET4RM48Cw
jbMXo0IMDe/XQIU/EPtXb8fqOXKeLuv6NyAFPCaroGet6DCGsGrqwrZ12AGEF8tL
pRhX6US+nx/ogXfsTpSwClXWrQkQFo9kRE4+xSSc62ZTKMh4QSOmgdxFMtjnJsgn
dtcBhVgq+RQQTsVWf3b8FphM201zQnCFHjGs7dDYL7cF68po5wNqnTWLdamTxbjO
DVboz85SC3mQG7mzcL8j5X1Jz+xJ5o228Cg4JYIjZlCw1zEakLePsYCbF7nd8Ykt
lypzHmw/PQ7MYsJJ9MBSkrwzqR/umY8TBZsuJTA8/iylNrC7ElQRzC0MzNGS
-----END RSA PRIVATE KEY-----
"""

verifyKey = """
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEArseWOZbqb74FUcqDbbXd
eYDhR4qZ8qzSwhMI2AVK+Ex69tXoI6mYLLKde92gFRrrD/CQOrDAX4HPEjJwA9l6
HdWtsxtQUMrsycox1AEPxIbZHNsHL5i/G+CkRfUUNi5Up4WOA4Z1CfLhEzxJMPfw
QbBIPQOM4g7gTUiDjoB9KU7WWXN+os5cEoWSOKT/2xLBRHJPuq8ysZ7XblFaLGr2
sIgg48PZ7d1FgOzUuh68/XOY5VJhfraZam4K85pvgNESIv0NEFBAFwsWwiQc/m0A
5tTiCdKV4/Gcb4g2mEvshgXm7yDubRgb+cAtDE5+Qxnmof0s4mHB5dEGerYLrcp0
mEhZyaR5eZpIGVuNDGFbbZksbkI3r+aLTkKer9QlbcJl9gzGUjgVWJHGdYiRAWQU
RPUpKdcHobjXwvArehAaBi3fMNXj5wbkAYKos9qXOO1YKX7EYAlAAMNamA4elaJ2
dBl5a/8uCFxIebRpZHIhHqyS7pS4SJfEF8W1hZ1fkujz4VePCo/rhKLHhGd7GOVd
3EGGr6OJ0vGHnBqF0PhaVr5VJPDRfvQxAigW6k0QaGkqItRKtri9QFDGi0Vu4xmi
gtr7EyW5Quw+rikHNOC0WAfrwtRt4qU4wvf6gN51ETG1N5I/+d1ethmHurdrL7Ip
BBsVeb/OwAwva1nsNkyf7x8CAwEAAQ==
-----END PUBLIC KEY-----
"""