[app]
name = "golang-grpc-base-project"
address = "localhost:5000"
debug = true

[pprof]
address = "localhost:6060"

[log]
payload = true

[database]
url = "mongodb://root:123456aA%40@localhost:27017"
name = "base"